client/package-lock.json, client/package.json, client/src/components/CodePlayground.jsx, client/src/index.css, client/src/pages/CoursePlayer.jsx
Linked Issue:
Connected to #8
Changes Made:
Added in-browser code editor
Enabled secure JS execution
Included syntax highlighting and autocomplete
Optional code templates support
Testing:
Manually tested: code runs as expected in lesson page
Checklist:
New branch used
No console errors
Follows contribution guidelines
=> feat: Implement Interactive Code Editor/Playground Integration (#8)

client/src/pages/Signup.jsx
---
title: "PR: Add custom JS form validation to signup page"
labels: "level 2"
assignees: "MehakGo"
---
---
- **Added:** Custom JavaScript validation for signup form fields.  
- Email must be a valid email format  
- Phone number must be a valid 10-digit number  
- Password must be at least 6 characters  
- **Fixed:** Disabled "Create Account" button until all fields are valid  
- **Updated:** UI to show real-time error messages below invalid fields  
---
**Test case 1**  
Steps: Enter invalid email (e.g., `mmm`) → Expected: Shows error `"Enter a valid email address"`  
Result: ✅ Works as expected  
**Test case 2**  
Steps: Enter invalid phone number (e.g., `aaa`) → Expected: Shows error `"Enter a valid 10-digit phone number"` …
=> Add Feature : Custom JS Form Vakidation for signup page

client/src/components/NavBar.jsx, client/src/pages/Home.jsx
To enhance the user experience and improve website navigation, we have incorporated navigation arrow buttons within the navbar. These arrow buttons are strategically positioned to facilitate seamless traversal of the page content. Specifically, we've implemented both top-to-bottom and bottom-to-top navigation, allowing users to effortlessly jump to the beginning or end of the page with a single click. This addition provides a more intuitive and efficient way for visitors to explore and access information, regardless of their current position on the webpage.
=> added top-down and down top button at navbar

client/src/pages/Home.jsx
---
about: Enchancement of UI and fixed the overlap of an component in the UI 
title: "PR: Fixed the issue of responsiveness for small screens  "
---
- [x ] Connected to #issue_number32
I Just updated the code for responsiveness but didn't touch other code making its functionalities same as before code format for the file using prettier extension the. More details and output can be seen in the image displaying before and after
---
- Added: Made the floating component responsive by increasing its margin in smaller screens enables it to be visible and doesn't have any overlapping issue.
- Fixed: Overlaping in UI is fixed
- Updated: Just updated the code for responsiveness but didn't touch other code making its functionalities same as before
---
---
If any improvements …
=> Fixed #issue32 responsive issue for smaller screens

client/src/pages/Courses.jsx, client/src/pages/Home.jsx
---
about: Fixed the #issue31 
title: "PR: Enchance the ui and removed the excessive space making the ui look cleaner "
---
- Added: Made the styling as grid intead of flex making the ui look better and clean without excessive space around it in courses
- Fixed: #issue31
- Updated: Updated the code for the ui enhancement and didn't touch the code apart from it making the functionality same as before
- 
---
---
If any changes needed or modification need comment down and suggestions are welcomed .
=> Issue 31 fix excessive space

client/package-lock.json, client/package.json, client/src/assets/json/roadmap.json, client/src/assets/json/skillbasedRoadmaps.json, client/src/pages/Roadmap.jsx
---
title: "Roadmaps: UI Enhancements, Search Functionality & JSON Update"
labels: "GSSoC, Level 3, Enhancement, Style Enhancement"
assignees: Amogh Kashyap S N
---
---
- Added: Search functionality to quickly find specific roadmap items
- Added: Enhanced UI for roadmaps with improved layout and styling
- Fixed: Minor UI inconsistencies across roadmap components
- Updated: Roadmap JSON file with latest structured data
---
---
|<img width="1756" height="738" alt="image" src="https://github.com/user-attachments/assets/5ebd2a00-72ce-4c10-883f-a86ee8b3ede9" />| <img width="1747" height="807" alt="image" …
=> Roadmaps: UI Enhancements, Search Functionality & JSON Update

Readme.md, client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/HomePageComponents/Contributor.jsx, client/src/pages/ContributorGuide.jsx, client/src/pages/Home.jsx
---
title: "PR: [Brief Description]"
labels: documentation, good first issue, gssoc25, level 2
assignees: "Amogh Kashyap S N"
---
---
- Added: Contributor Guide page with essential Git commands, details about pull requests, FAQ section for basic Git questions, and learning resources. Included links to official Git documentation and project repository. Ensured the page is fully responsive.
- Fixed: Improved navigation by providing direct access to Git docs and repository contribution links.
- Updated: README with information about the new Contributor Guide so contributors can easily discover and use it.
---
---
THERE IS NO BEFORE …
=> Added a new page of contributor guide and a new component in home page 

client/src/pages/Roadmap.jsx
---
title: "PR: 🐞 Fix Counter Increment Bug"
labels: "bug , gssoc25 , level2"
assignees: ""
---
---
-Fixed counter logic in **Roadmap.jsx**  
---
Before: 
After:
---
=> Fixed the Roadmap Counter issue

client/src/components/UserActivity.jsx, client/src/pages/CoursePlayer.jsx, server/controllers/coursesController.js, server/models/userActivitySchema.js, server/routes/coursesRoute.js
This pull request fixes the dashboard utility by implementing the course enrollment functionality and tracking user activities.
Changes:
* Course Enrollment:
* Added an "Enroll" button to the CoursePlayer page.
* Implemented the enrollCourse function to handle course enrollment.
* The "Enroll" button is disabled if the user is already enrolled in the course.
* Activity Tracking:
* A course_enrolled activity is created in the database when a user enrolls in a course.
* The new activity is fetched and displayed on the dashboard.
Fixes: #10 
How to Test:
1. Go to a course page that you are not enrolled in.
2. Click the "Enroll" button.
3. Verify that you are enrolled in the course and the "Enroll" button is disabled.
4. Go to the dashboard and verify that the "course_enrolled" activity is …
=>  feat(dashboard): Implement course enrollment and activity tracking

client/src/components/NavBar.jsx
---
title: "PR: Unified Login/Signup Button for Improved UX"
labels: "GSSOC25 , level-2"
---
---
- Added: Unified authentication button that handles both login and signup.
- Fixed: Redundant navigation logic for separate login and signup flows.
- Updated: UI layout to accommodate the new single-entry auth button.
---
- Test case 1: Clicked the unified button without being logged in → Prompted to choose between login or signup → Navigated successfully.
- Test case 2: Attempted to sign up with a new email → Redirected to signup flow → Account created successfully.
---
Before:
After:
---
---
=> Update single button for login/signup in navbar

client/src/pages/About.jsx, client/src/pages/Courses.jsx
---
title: "PR: Update the design of Courses Page to match Roadmaps UI"
labels: "style enhancement"
---
---
- Added: Enhanced background system with grid pattern and gradient overlay matching Roadmaps design
- Fixed: Inconsistent spacing and padding throughout the component
- Updated: Course grid layout from flexbox to CSS Grid with proper responsive breakpoints
---
- Test case 1: Page Load and Animation Performance
- Steps: Navigate to Courses page, observe initial load animations, scroll through sections
- Expected Result: Smooth staggered animations, 60fps performance, no layout shifts 
- Test case 2: Search and Filter Functionality
- Steps: Use search bar with various terms, click category filters, …
=> Update the design of Courses Page to match Roadmaps UI

client/src/components/Contributor.jsx
<h2 data-start="189" data-end="344">name: "📦 Pull Request"<br>
about: Submit changes for review<br>
title: "PR: Add background effect to Contributors section"<br>
labels: "enhancement"<br>
assignees: ""</h2>
<h2 data-start="346" data-end="364">📌 Linked Issue</h2>
&lt; issue  --&gt;
<ul class="contains-task-list" data-start="410" data-end="444">
<li class="task-list-item" data-start="410" data-end="444">
<p data-start="416" data-end="444"><input disabled="" type="checkbox"> Connected to #135 </p>
</li>
</ul>
<hr data-start="446" data-end="449">
<h2 data-start="451" data-end="469">🛠 Changes Made</h2>
<ul data-start="470" data-end="648">
<li data-start="470" data-end="563">
<p data-start="472" data-end="563">Added: Background effect (grid/animated pattern) applied to the <strong …
=> background of the contributor

client/src/pages/Dashboard.jsx
---
title: "PR: Update the design of Dashboard Page to match Roadmaps UI"
labels: "style enhancement"
---
---
- Added: Consistent backdrop blur effects and shadow styling across all dashboard cards
- Fixed: Visual consistency by applying the same color schemes and transition effects across all dashboard widgets
- Updated: Typography hierarchy using font-righteous for section headers to match other dashboard components
---
- Test case 1: Card hover animations
- Steps: Hover over "Continue Watching" and "Recent Activity" cards
- Expected Result: Cards should lift slightly (y: -4px) with animated borders appearing on top-right and bottom-left edges
- Test case 2: Dark/Light mode consistency
- Steps: …
=> Update the design of Dashboard Page to match Roadmaps UI

client/src/pages/NotesPage.jsx
- Replaced **Framer Motion animations** with **GSAP + ScrollTrigger** for smoother and more customizable animations.  
- Added **underline animation** for the "Notes & Resources" heading → expands from `0% → 100% width`.  
- Implemented **scroll-triggered animations** for Notes cards:  
- Fade-in effect  
- Slide-up with smooth easing  
- Staggered entry for better visual flow  
- Improved **responsiveness** of animations across breakpoints (mobile → desktop).  
- GSAP provides better performance and flexibility compared to Framer Motion for scroll-based animations.  
- Cleaner, more scalable animation control (easier to add future effects like parallax or stagger groups).  
- Enhances overall **user experience** with smoother, visually appealing transitions.  
- Heading underline now …
=> ✨ Implement GSAP ScrollTrigger for Notes Page with Responsive Animations

client/src/App.jsx, client/src/pages/GitNotes.jsx, client/src/pages/ReactPattern.jsx
Description
This PR addresses issue #140 by expanding the Git & Version Control section with detailed explanations, commands, and best practices.
Changes introduced in this PR:
✅ Added Git basics (installation, configuration, repository management)
✅ Covered staging, committing, branching, and merging
✅ Included advanced topics:
Git Aliases & Git Ignore
Git Hooks for automation
Cherry-pick, Reflog, and Bisect for debugging
Submodules and Worktrees
Squash commits for clean history
✅ Documented popular workflows (Feature Branch, Gitflow, Forking)
✅ Added Git security practices (signed commits, secrets handling)
✅ Included CI/CD integration with GitHub Actions/GitLab CI
✅ Added troubleshooting guide for common Git issues
Why this is useful:
Makes the Git & Version Control section more …
=> 📘 Added Advanced Git & Version Control Content (Closes #140)

client/src/App.jsx, client/src/pages/PythonNotes.jsx
Description:
Adding beginner-friendly Python basics content including explanations, examples, and code snippets for core concepts (variables, operators, conditionals, loops, functions, data structures, OOP, file handling, etc.). The section will be structured into ~25 topics with clear explanations and practical examples for easy learning.
Comment:
This contribution will make the Python Basics section more useful for new learners by combining explanations with examples and code snippets.
Thanks You!
Sample image :
=> Adding Python Basics Content

client/src/components/MobileMenu.jsx, client/src/pages/Roadmap.jsx
**Assignees** : @SaiSruthisri  
**Labels** : **GSSoc25 , Level 2**  
*****
---
- Added the Bookmarks for roadmap in the navbar 
---
- In the roadmap page 
---
--- 
Please let me know for any further changes required.
Thank you!
=> Added Bookmarks for roadmap in navbar

client/src/layouts/AdminUsers.jsx
---
title: "PR: Update the design of Admin Users Page to match Roadmaps UI"
labels: "style-enhancement"
---
---
- Added: 
- Card-based layout system replacing the original table design
- Gradient background patterns and animated grid overlay
- Interactive stats cards with hover animations and role-based metrics
- Animated border effects on card hover (right and bottom borders)
- Enhanced search control panel with integrated icon and styling
- Sorting controls section with visual button states
- Fixed:
- Responsive layout issues with proper grid breakpoints
- Dark/light theme consistency across all components
- Updated: 
- Complete visual redesign to match AdminContacts page styling
- Color scheme to …
=> Update the design of Admin Users Page to match Roadmaps UI

client/src/pages/Login.jsx, client/src/pages/Signup.jsx
**Assignees** : @SaiSruthisri 
**Labels** :  **GSSoc25** 
*****
---
- Added Google button in Signup.jsx
- Changed the Login page google button
---
Login page
Signup page
---
=> Added improved Google Oauth buttons

client/src/pages/ErrorPage.jsx
**Assignees** : @SaiSruthisri  
**Labels** :  **GSSoc25 , Level 3**  
*****
---
- Updated UI to match the Roadmap.js page  
---
-  Before 
-  After 
---
---
=> Redesign 404 Page to match Roadmaps page UI 

client/src/components/Footer.jsx
I have added the link for address and mail.
Please check and inform me if any thing this wrong
=> addinglink for map and mail

client/public/manifest.json, client/src/components/CardBody.jsx, client/src/components/PersonalInfoEdit.jsx, client/src/context/PopupContext.jsx, client/src/pages/Dashboard.jsx, client/src/store/auth.jsx, server/controllers/userController.js, server/routes/userRoute.js
---
title: "PR: updated dashboard with personal profile section"
labels: ""
assignees: ""
---
---
- Refactor Dashboard and Manifest: Simplified icon structure in `manifest.json `and revamped Dashboard layout with tab navigation for learning, watchlist, and bookmarks. Removed unused states and components for improved performance.
=> updated dashboard with personal profile section

client/src/components/Footer.jsx
---
about: Submit changes for review 
title: "PR: Fixed footer text formatting issue"
labels: ""
assignees: "Pooja67"
---
---
- Fixed: Corrected typo in footer address
---
---
| Before |
| After |
---
---
=> Resolved footer typo issue

client/src/layouts/CourseLayout/AdminCourses.jsx
---
title: "PR: Update the design of Admin Courses Page to match Roadmaps UI"
labels: "style-enhancement"
---
---
- Added: Animated borders on card hover (right and bottom borders)
- Updated: Applied exact gradient backgrounds (from-blue-50 to-indigo-50 dark:from-gray-800 dark:to-secondary-1000)
---
---
Before:
After:
---
---
=> Update the design of Admin Courses Page

client/src/components/Footer.jsx
---
title: "PR: Style : Redesign Footer Page to match Roadmaps UI"
labels: "style enhancement, level 3, gssoc25"
---
---
- Added: 
- Background grid pattern matching roadmaps page design with bg-[size:30px_30px] and bg-grid-pattern-dark/light classes.
- Gradient overlay on grid background for better readability while maintaining visual texture.
- Updated: 
- Footer main background to use glassmorphism gradient (bg-gradient-to-br from-blue-50 to-indigo-50) consistent with roadmap cards.
- All footer sections (About Us, Quick Links, Learning Paths, Contact) converted to individual glassmorphism cards with backdrop blur and transparent borders.
- Newsletter subscription section enhanced with stronger …
=> Style : Redesign Footer Page to match Roadmaps UI

client/src/index.css
---
title: "PR: Modified the CallToAction card's UI (Ready to start your learning journey " card's UI to get along better with the light mode and dark mode
labels: "bug" , "enhancement","gssoc25","level 2"
assignees: "Granger007"
---
---
- Fixed: inconsistent UI 
- Updated: index.css file in  /client/src/ to ensure the shades are softer and get along better with the light and dark mode.
---
| [
] | [
] |
=> feat : Update index.css

server/controllers/authController.js, server/utils/OTPemailTemplates.js, server/utils/sendEmail.js
**Assignees** : @SaiSruthisri  
**Labels** :  **GSSoc25 , Level 2**  
*****
---
- Enhance OTP email to make it more professional 
---
---
=> Enhance OTP email 

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/MobileMenu.jsx, client/src/components/PageHeader.jsx, client/src/components/QuestionCard.jsx, client/src/components/QuestionDetail.jsx, client/src/components/QuestionsGrid.jsx, client/src/context/QuestionContext.jsx, client/src/main.jsx, client/src/pages/QuestionPage.jsx, package-lock.json, package.json
---
title: "PR: Complete frontend for Question & Reply pages"
labels: ""
assignees: ""
---
---
- Added: Complete frontend UI for the Question page
- Added: Reply page with threaded replies and inline reply editor
- Updated: Styling, dark/light theme toggle, and vote/bookmark interactions
---
- Test case 1: Open Question page, verify question content renders correctly
- Test case 2: Add main reply and inline replies, verify threaded structure
- Test case 3: Test upvote/downvote and bookmark buttons
- Test case 4: Dark/light theme toggle works correctly
---
---
---
- Frontend is complete for Question and Reply pages; backend integration for submitting replies is pending.
=> Question Page

client/src/assets/courses/rust.json
Description
Problem
Our course catalog currently lacks Rust programming language resources—an increasingly important tool for systems programming, performance-critical applications, WebAssembly, and safe concurrency. Without Rust, learners miss the opportunity to explore one of the fastest-growing modern languages for reliable and memory-safe development.
Potential Impact
Target Users: Systems programmers, backend developers, WebAssembly engineers, students interested in modern memory-safe languages.
Value Provided:
Fills the gap in systems programming education.
Introduces learners to Rust’s ownership and safety model.
Prepares developers for high-performance and reliable application development.
Activity Checklist
Verify all links and images are functional.
Add rust.json under …
=> Feature: Add Rust Course to the Courses Section

client/src/assets/courses/javafullstack.json
---
name: "📦 Adding JAVA Full stack to list of Courses"
about: submit changes for review 
title: "Feature: Adding JAVA Full stack to list of Courses"
labels: "enhancement"
New feature: [gssoc25] (https://github.com/Roshansuthar1105/Codify/issues/143)"
assignees: "aaqeebpinjari"
---
---
- Added:  javafullstack.json format in the course assets list
---
---
---
-- Hey roshan, i have made the javafullstack.json as u mentioned me, but i was getting problem how to actually made it visible, course section, i have figured out that modal section has courseschema.js and fetching from database, but was not preety sure, i case u give me a rough info how i can add it then sure i will implement it, i am eager to learn more about it, surely waiting for ur reply, weather this is enough like submitting …
=> Added the Json format for Java full stack

client/src/assets/courses/lld.json
---
name: "Adding LLD course to the Courses Session "
about: submit changes for review 
title: "Adding DSA course to the Courses Session"
labels: "enhancement"
New feature: [gssoc25] (https://github.com/Roshansuthar1105/Codify/issues/145)"
assignees: "aaqeebpinjari"
---
---
- Added:  lld.json format in the course assets list as u mentioned me
---
---
-- Hey roshan, i have made the lld.json as u mentioned me, and here by i am attaching it here , review and let me know there is any more requirements or any type of feedback needed by my side, would love to collaborate
and sorry for such late PR . so was not able to make things on time, from now onwards ill be sure be active, here by is my another PR.  Looking forward for more collaboration.
=> Added best LLD courses link 

client/src/pages/Notes/JavaScriptFundamentals/JsTopics/VariableNamingRules.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/WhatAreVariables.jsx
**Hi team 👋**
This PR introduces two new notes pages: one explaining how JavaScript variables work and another detailing naming conventions, common rules, and best practices for variables.
---
- No dedicated content covering the basics of JS variables or their naming conventions.
- Beginners lacked clear examples and best practices for meaningful and valid variable names.
---
- Added an in-depth "JavaScript Variables" topic with explanations about declaring variables using `var`, `let`, and `const`, supported by essential usage examples.
- Added a full page for "JavaScript Variable Naming Rules" summarizing rules and conventions:
- Valid starting characters for variable names.
- Allowed characters (`letters`, `numbers`, `_`, `$`) and prohibited spaces/symbols.
- Case sensitivity and …
=> Added Pages for JavaScript Variables & Naming Rules

client/src/pages/Notes/JavaScriptFundamentals/JsTopics/OperatorsAndExpressions.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/PrimitivesAndObjects.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/VarLetConst.jsx
**Hi team 👋**
This PR introduces three new foundational JS topics: the distinction between primitives and objects, an overview of operators and expressions, and a comparison of var, let, and const.
---
- There was no dedicated content breaking down JavaScript's primitive types vs objects, leaving gaps in understanding value vs reference types.
- Key JS operator types and expression formats were undocumented, making it harder to learn syntax and common patterns.
- Many users lacked clear guidance on when to use var, let, or const and the differences between their behavior.
---
- Added a page detailing the core differences between primitives (number, string, boolean, null, undefined, symbol, bigint) and objects (Object, Array, Function, etc.), including how values and references work.
- …
=> Added Topics: Primitives & Objects, Operators & Expressions, Var vs Let vs Const

client/src/App.jsx, client/src/components/CardBody.jsx, client/src/pages/Roadmap.jsx
---
title: "PR: removed the loader appearing while saving the card"
labels: "Bug Level3 GSSOC2025"
assignees: ""
---
---
- Fixed: Refactor CardBody component: removed loading context usage and related loading state management in watchlist handling
---
- Step 1: Navigate to Courses
- Step 2: Try to Save the course (Loader won't be coming, direct saved successfully toast is coming)
---
=> removed the loader appearing while saving the card.

client/src/components/HomePageComponents/CallToAction.jsx, client/src/components/HomePageComponents/ChooseUs.jsx, client/src/components/HomePageComponents/Contributor.jsx, client/src/components/HomePageComponents/CreatorsContainer.jsx, client/src/components/HomePageComponents/FAQ.jsx, client/src/components/HomePageComponents/NewsLetter.jsx, client/src/components/HomePageComponents/Testimonials.jsx, client/src/pages/Home.jsx
---
title: "PR: Redesign Home Page UI"
labels: "style enhancement, gssoc25, level 3"
---
---
- Added: 
- Background grid pattern matching roadmaps page design with bg-[size:30px_30px] and bg-grid-pattern-dark/light classes.
- Gradient overlay on grid background for better readability while maintaining visual texture.
- Updated: 
- main background to use glassmorphism gradient (bg-gradient-to-br from-blue-50 to-indigo-50) consistent with roadmap cards.
---
---
---
---
=> Style : Redesign Home Page UI

client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/ArraysAndMethods.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/StringsInJS.jsx
**Hi team 👋**
This PR adds routing for several essential JavaScript topics—making navigation more modular and expandable—and introduces two new content sections on strings and arrays.
---
- Previous implementation lacked distinct, dedicated routes for topics like for loops, while loops, functions, and ternary operators.
- The notes section did not cover string basics or array features and methods, leaving gaps in foundational knowledge.
---
- Added new routes for the following JS topics:
- For loops
- While loops
- Functions
- Ternary operator
- Created a "Strings in JavaScript" note covering string declaration, usage, common methods (length, slice, split, join, etc.), and practical examples.
- Added a topic for "Array and Methods":
- Explained array creation (literal, constructor), …
=> Added Routes for JS Topics & New Notes on Strings and Arrays

client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/LoopsWithArrays.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/MapFilterReduce.jsx, client/src/pages/Notes/JavaScriptFundamentals/components/JsSideBarData.json
**Hi team 👋**
This PR adds two important new topics for JavaScript learners: looping through arrays using various techniques and leveraging powerful array methods like `map`, `filter`, and `reduce`.
---
- The documentation lacked detailed explanations of different ways to iterate through arrays.
- No clear examples of modern array methods that transform, filter, and aggregate array data.
---
- Added a "Loops with Arrays" topic, showing how to use for, forEach, for...of, while, and do-while loops to process array items, with clear code snippets.
- Introduced a "Map, Filter and Reduce" section:
- Explained syntax and use cases for `map` (transform arrays), `filter` (select items), and `reduce` (accumulate data).
- Included simple, practical examples illustrating how each method works for …
=> Added Topics: Loops with Arrays & Map, Filter, Reduce Methods

client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/DateInJS.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/MathInJS.jsx
**Hi team 👋**
This PR adds two new reference topics—using Dates and Math in JavaScript—providing foundational API knowledge for time handling and mathematical operations in JS apps.
---
- The docs previously lacked guidance on creating, manipulating, and formatting dates, limiting users’ ability to handle time and events.
- There was no reference for JavaScript’s Math object methods and their practical arithmetic use cases.
---
- Added a "Date in JS" topic covering:
- How to create Date objects (`new Date()`, from string, from components).
- Key Date methods (get/set year, month, day, etc.) and converting to string.
- Examples for retrieving, updating, and formatting dates in common scenarios.
- Added a "Math in JS" topic explaining:
- Use of the `Math` object for arithmetic, rounding, …
=> Added Topics: Date and Math in JavaScript

client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/BooleanInJS.jsx, client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/NumberInJS.jsx
**Hi team 👋**
This PR expands the JS notes section with comprehensive introductions to numeric operations and boolean logic—two core data types for millions of JS workflows.
---
- Docs previously lacked guidance on number handling, conversion, calculations, and special values (`NaN`, `Infinity`).
- No coverage of Boolean type, its creation, common usage patterns, and practical examples.
---
- Added "Numbers in JavaScript," covering:
- Declaration (integers, floats), conversion between types, important constants (`MAX_VALUE`, `MIN_VALUE`, `NaN`, `Infinity`) and pitfalls.
- Arithmetic operators, type coercion, `parseInt`, `parseFloat`, and mathematical operations.
- Real-world code samples for numeric logic and precision.
- Added "Boolean in JavaScript," explaining:
- The boolean type, …
=> Added Topics: Numbers & Boolean in JavaScript

client/src/pages/Roadmap.jsx
Fixes #328
---
- Added: icons for the languages and frameworks available
---
---
---
---
=> ufeat: add skill icons for enhanced roadmap visualization

client/src/pages/Courses.jsx
Refactor loading state management
Fixes #329
---
- Updated: loading state such that when bookmarking the loader doesnt block the whole page
---
---
---
---
=> refactor loading state management from fetchWatchlist function

client/src/components/MobileMenu.jsx, client/src/components/ThemeColorSelector.jsx
made sure the color popup closes after closing the sidebar 
---
- Added: [Description]
- Fixed: [Description]
- Updated: [Description]
---
---
---
---
=> Enhance MobileMenu and ThemeColorSelector components with improved state management

client/src/App.jsx
---
title: "PR: Enhance ScrollToTop functionality"
labels: ""
assignees: ""
---
---
- I changed `ScrollToTop `in `App.jsx` to skip scrolling on the initial mount (refresh) and only scroll to top on subsequent route changes.
=> Enhance ScrollToTop functionality

client/src/components/QuestionCard.jsx, client/src/layouts/CourseLayout/AddNewCourse.jsx
---
title: "PR: Update the design of Questions Page"
labels: "style enhancement, level 3, gssoc25"
---
---
- Added: Animated borders on card hover (right and bottom borders)
- Updated: Applied exact gradient backgrounds (from-blue-50 to-indigo-50 dark:from-gray-800 dark:to-secondary-1000)
---
---
Before:
After:
---
---
=> Update the design of Questions Page

server/controllers/questionController.js
This PR fixes the voting logic for questions by making upvotes and downvotes toggleable
---
Enable toggle for question votes:
- Upvotes/downvotes can now be removed by clicking again.
- Switching votes auto-removes the opposite.
---
---
---
---
=> Refactor upvote and downvote logic to streamline user interactions and ensure accurate vote counts

client/src/App.jsx, client/src/pages/Notes/FallBackNotes.jsx, client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx, client/src/pages/Notes/JavaScriptFundamentals/components/JsHeroPage.jsx, client/src/pages/Notes/NotesData.js, client/src/pages/Notes/NotesPage.jsx
**Hi team 👋**
This PR delivers several improvements: lazy loading for JS imports is removed to fix layout shifts, the notes components/files are standardized in `/pages/notes/`, and the NotesPage is fully rebuilt with framer-motion for smoother UI. Plus, visual cues (link and docs icons) are introduced on notes cards.
---
- Lazy loading JS components formerly caused layout shifts and inconsistent initial render.
- Notes-related code was scattered across folders, with multiple naming and filepath inconsistencies.
- The NotesPage UI/UX needed modernization and more actionable visual indicators for topic resources.
---
- **Removed lazy loading:** All JS imports now load eagerly, eliminating layout and content shifts throughout topic transitions.
- **File/folder conventions:** Relocated all …
=> Refactor: Remove Lazy Loading, Standardize Notes Structure, Rebuild NotesPage with Motion Enhancements

client/src/components/Footer.jsx, server/controllers/authController.js, server/models/visitorCounterSchema.js
---
Labels: "gssoc25" , "Level 3"
Assignees: "@SaiSruthisri"
---
---
- Added: The total visitors count in the footer section so, every time anyone refreshes or visits the website , the visitors count is updated
---
>The visitor count appears on all pages having the footer section
=> Added visitors count

client/src/pages/Courses.jsx, client/src/store/auth.jsx, server/controllers/authController.js, server/controllers/coursesController.js, server/models/courseSchema.js, server/routes/coursesRoute.js
**Assignees** : @SaiSruthisri  
**Labels** : **GSSoc25 , Level 3**  
*****
---
- Added a new backend API route: `GET /courses/:courseCategory`.
- Fetches all courses from the database matching the given category.
- Returns success `true` and course list in `data` field.
- Handles cases when no courses exist → returns empty array with success `true`.
- Proper error handling for server or database errors.
>Have integrated this backend route to the frontend, will remove it if it's not planned to be integrated with frontend yet.
---
**Request:**  
`GET /api/v1/courses/python`  
**Response:**
```json
{
"success": true,
"count": 1,
"data": [
{
"_id": "68cf9b32805cfd3ef75a6c2f",
"course_category": "python",
"course_title": "Python Tutorial for Beginners | Learn Python in 1.5 Hours", …
```
=> Add Backend API for Fetching Courses by Category

client/package-lock.json, client/src/pages/Roadmap.jsx
---
title: "PR: [Brief Description]"
labels: ""
assignees: ""
---
- [ /] Connected to #419 
---Closes #419 
- Added: [Description]
- Fixed: [Description]
- Updated: [Remove the background property applying to the icon]
---
- Test case 1: [cd client +npm run dev]
- Test case 2: [ Expected Result]
---
before==
after==
https://github.com/user-attachments/assets/7d520a71-6649-46a9-9cd1-fd7e80535eb0
---
- [/ ] Added code comments
---
- [// ] Created a new branch for PR
- [ /] Have stared the repository
- [/ ] Follows [JavaScript Styleguide](CONTRIBUTING.md#javascript-styleguide)
- [ /] No console warnings/errors
- [ /] Commit messages follow [Git …
=> [ENHANCE] :enhance  bg of icons on roadmap

SECURITY.md
---
title: "PR: Add SECURITY.md for vulnerability reporting and best practices"
labels: "documentation, security"
assignees: ""
---
---
- Added: `SECURITY.md` file with responsible disclosure policy
- Included: Contact emails and GitHub issue link for reporting vulnerabilities
- Documented: Authentication methods, sensitive data handling, and deployment recommendations
---
- Verified markdown renders correctly on GitHub
- Confirmed links and formatting are functional
---
| N/A    | New `SECURITY.md` file visible in repo root |
---
---
---
This PR helps Codify align with GitHub’s security disclosure standards and improves contributor clarity. No breaking changes introduced.
=> docs: add SECURITY.md for security practices

client/src/App.jsx, client/src/components/CodeEditor..jsx, client/src/components/NavBar.jsx
---
title: "PR: Added new features in editor playground "
labels: "level 3"
assignees: "shivin1016"
---
---
- Added: Clear console button with shortcut keys -> ctrl + i and for run code ctrl + enter 
---
- [✅] Ran unit tests (`npm test`) 
---
| Before |
|After|
https://github.com/user-attachments/assets/2883cced-b186-4634-aec3-aa3da74556a0
---
- [✅] Added code comments
---
- [✅] Created a new branch for PR
- [✅] Have stared the repository
- [✅] Follows [JavaScript Styleguide](CONTRIBUTING.md#javascript-styleguide)
- [✅] No console warnings/errors
- [✅] Commit messages follow [Git Guidelines](CONTRIBUTING.md#git-commit-messages)
=> added new feature clear console btn and shotcut keys for run and clear console 

client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/ConfigGit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitArchitecture.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInitRepository.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInstallation.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitAdd.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitCommit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitStatus.jsx
**Hi team 👋**
This PR adds detailed documentation for three foundational Git commands: `git add`, `git status`, and `git commit`. These notes guide both beginners and intermediate users through essential version control actions for any project.
---
- Learners lacked clear explanations of how to stage files, inspect current changes, and create commits in their local repository.
- The absence of usage examples for these common commands made it harder for new contributors to use Git effectively.
---
- **Added:** "git add" notes describing how to stage new and modified files for the next commit. Includes `git add <file>`, `git add .`, and advises on tracking files for version control[web:439][web:437].
- **Added:** "git status" section showing how to check the current branch, see …
=> Add git commit, git add, and git status Notes

client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/ConfigGit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitArchitecture.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInitRepository.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInstallation.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitAdd.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitCommit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitDiff.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitLog.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitReset.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitStatus.jsx
**Hi team 👋**
This PR adds detailed notes for three important Git commands: `git reset`, `git log`, and `git diff`. These notes provide essential skills for managing change history, inspecting commit history, and comparing file changes.
---
- The documentation lacked clear guidance on how to undo/stage changes with `git reset`, view repository history with `git log`, and compare file differences using `git diff`.
- Learners and contributors need these commands to navigate, audit, and manage their Git workflows effectively.
---
- **Added:** `git reset` notes explaining the command's role in moving branch pointers and modifying the staging area and working directory.
- Includes explanation of modes: `--soft`, `--mixed` (default), `--hard`.
- Practical examples for unstaging files, undoing …
=> Add Notes for git reset, git log, and git diff Commands

client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BranchAndMerge/GitBranches.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BranchAndMerge/GitDeleteBranches.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BranchAndMerge/GitMerge.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BranchAndMerge/MergeTypes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BranchAndMerge/ResolvingMergeConflicts.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/ConfigGit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitArchitecture.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInitRepository.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GetStartedWithGit/GitInstallation.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitAdd.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitCommit.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitDiff.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitLog.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitReset.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitCommands/GitStatus.jsx
**Hi team 👋**
This PR adds comprehensive notes on deleting Git branches locally using `git branch -d` and force-deleting with `git branch -D`. It explains the differences, common errors, and best practices to safely manage branch cleanup.
---
- There was no clear guidance for safely deleting Git branches, avoiding errors like deleting the current branch or deleting unmerged branches without caution.
- Contributors need to understand the implications and use cases for both regular and force deletion.
---
- **Added:** Explanation of `git branch -d <branch_name>`
- Deletes a local branch only if fully merged.
- Safe default to prevent data loss.
- **Added:** Explanation of `git branch -D <branch_name>`
- Force deletes local branches, ignoring merge status.
- Useful for cleaning stale or …
=> Add Notes for Deleting Branches (git branch -d and git branch -D)

client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/GitFetch.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/GitPushPull.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/GitRemoteAdd.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/RemoteRepository.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/TrackingBranches.jsx
**Hi team 👋**
This PR introduces new notes covering how to use `git fetch` to safely update remote-tracking branches, and explains the concept of tracking branches and their role in collaborative workflows.
---
- The documentation didn't yet cover how `git fetch` updates local knowledge of a remote repository without changing working files, an essential habit for all contributors.
- There was no existing explanation of what tracking branches are or how they help streamline synchronization between local and remote work.
---
- **Added:** "Git Fetch" documentation:
- Details on how `git fetch` works, why it’s safe (doesn’t modify local files), and when to use it vs. `git pull`.
- Examples for fetching all branches, a specific branch, and the use of flags like `--all`.
- Clear workflow for …
=> Add Notes: Git Fetch & Tracking Branches

client/src/pages/Notes/PythonFundamentals/PyTopics/PythonBasics/ConditionalStatements.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/PythonBasics/StringFormatting.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/PythonBasics/TypeCasting.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/PythonBasics/VariablesDataTypes.jsx, client/src/pages/Notes/PythonFundamentals/PythonFundamentals.jsx
**Typecasting in Python**
- Covered all type conversions: implicit and explicit casting
- Practical examples converting strings to integers, floats to integers, and vice versa
- Real-world use cases like user input processing, mathematical operations, and file data parsing
- Common pitfalls explained (loss of precision, invalid conversions)
- Best practices section highlighting safe casting using try-except blocks
**String Formatting in Python**
- Explained all formatting techniques: % operator, str.format(), f-strings
- Showed variable interpolation with dynamic values
- Advanced formatting: precision control, alignment, padding, number formatting
- Practical examples including receipts, reports, and dashboard displays
- Best practices ensuring readability and consistency in formatting …
=> Added python basic notes

client/package-lock.json, client/package.json, client/src/components/CodeEditor..jsx
---
title: "PR:Added java Langauge and hover effects for knowing shortcuts for run code and clear code"
labels: "3"
assignees: "Shivin1016"
---
- [✅] Connected to #449 
---
- Added: Java feature langauge and hover effects on run code and clear console button for shourtcuts
---
---
| Before |
| After |
https://github.com/user-attachments/assets/549c5cc3-8bea-4f47-807c-169fc6130063
https://github.com/user-attachments/assets/ca59625d-0b12-4f14-826e-ce06a1568d82
---
- [✅] Updated README/docs
- [✅] Added code comments
---
- [✅] Created a new branch for PR
- [✅] Have stared the repository
- [✅] Follows [JavaScript Styleguide](CONTRIBUTING.md#javascript-styleguide)
- [✅] No console warnings/errors
- [✅] Commit messages …
=> Added java lang and hover on buttons for shortcuts

client/src/pages/Notes/PythonFundamentals/PyTopics/Introduction/PyIntroduction.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/Introduction/PythonInstallation.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/Introduction/RunningPythonCode.jsx, client/src/pages/Notes/PythonFundamentals/PythonFundamentals.jsx
**What’s Added**
Created three separate React components for Python basics:
- PyIntroduction.jsx – Covers Python introduction, history, and features.
- PythonInstallation.jsx – Explains installation process on Windows, Mac, Linux, pip setup, and IDEs.
- RunningPythonCode.jsx – Demonstrates different ways to run Python code (interactive shell, scripts, IDEs, online interpreters).
**Why This Change?**
- Keeps each Python learning section modular and easy to maintain.
- Makes navigation cleaner with separate routes for each topic.
- Improves readability and scalability for future Python topics.
**Screenshots:**
**Gssoc lables:**
- level3
- frontend
- enhancement
@Roshansuthar1105 this pr is ready to be merged
=> Add pynotes3

client/src/components/NavBar.jsx, client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/CodeReviewBasics.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/ForkingWorkflow.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/GitClone.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/PullRequests.jsx
**Hi team 👋**
This PR enhances the Git documentation by adding clear explanations and workflows for forking repositories, cloning projects, submitting pull requests (PRs), and participating in basic code review. Each section is aimed at helping contributors participate efficiently in collaborative and open-source projects.
---
- Contributors lacked comprehensive notes for:
- Copying and working on remote repositories (forking and cloning).
- Participating in open-source via pull requests.
- Engaging in code review, an essential part of quality assurance and team workflow.
---
- **Added:** **Git Fork Workflow**
- What forking a repository means in the context of Git and GitHub.
- How to fork a repo, clone the fork, sync with upstream, and maintain feature branches.
- Complete step-by-step …
=> Add Notes: Git Fork, Git Clone, Code Review Basics, and Pull Requests

client/src/components/NavBar.jsx, client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/CodeReviewBasics.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/ForkingWorkflow.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/GitClone.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/CollabrativeWorkflow/PullRequests.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitUndoingChanges/GitCheckoutVsRestore.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitUndoingChanges/GitResetExplained.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitUndoingChanges/GitRevert.jsx
**Hi team 👋**
This PR adds comprehensive documentation for undoing changes in Git, covering essential commands and workflows for recovering, reversing, and resolving mistakes at different stages of the development process.
---
- The previous notes lacked clear coverage of how to undo mistakes in Git, whether before or after committing, staging, or pushing changes.
- Contributors need reference examples for safely reverting, resetting, or restoring work without losing valuable history or disrupting team workflows.
---
- **Added:** Explanations and workflows for common undo commands:
- `git revert`: Safely undoes public commits by creating a new commit that reverses previous changes — ideal for shared repositories and fixing mistakes in project …
=>  Add Notes for Undoing Changes in Git

server/package-lock.json, server/package.json, server/server.js
Adding self-pinging mechanism with cron job
---
- Added: cron job for self pinging
---
---
---
---
=> implement self-pinging mechanism with cron job

client/src/components/HomePageComponents/CallToAction.jsx, client/src/components/HomePageComponents/Testimonials.jsx
---
title: "PR: fixed in styles for call to action to adhere color schema change.
labels: "hacktoberfest"
assignees: ""
---
---
- On the Call to Action page, the styling did not align with the rest of the color scheme. This pull request updates the styles to ensure consistency across the site.
- In the Testimonials section, the "Start Journey" button was not clickable. This pull request fixes the issue by enabling it to navigate to the course page.
---
---
Before: 
After: 
---
---
=> Fix: fixed in styles for call to action to adhere color schema change.

client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/Dictionaries.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/NestedLoops.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/Strings.jsx, client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/TuplesSets.jsx, client/src/pages/Notes/PythonFundamentals/PythonFundamentals.jsx
**Enhanced Clarity & Structure**
- Organized concepts into clear, beginner-friendly sections
- Used consistent formatting for better readability
- Added concise explanations before diving into examples
**Added Depth & Practicality**
- Introduced advanced concepts with simple breakdowns
- Included real-world inspired examples for better understanding
- Provided best practices to encourage clean and reusable code
**Improved Learning Flow**
- Expanded examples from basic to advanced progressively
- Highlighted key takeaways at the end of each section
- Ensured smooth transitions between related topics
**Screenshot:**
**Gssoc labels:**
- level3
- enhancement
- frontend
@Roshansuthar1105 this pr is ready to merge
=> Added Datastructures Docs

client/src/pages/Notes/GitVersionControl/GitNotes.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/AdvanceGit/GitCherryPick.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/AdvanceGit/GitHooks.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/AdvanceGit/GitInteractiveRebase.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/AdvanceGit/GitRebase.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/AdvanceGit/GitSquashingCommits.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BestPractices/AvoidingLargeBinaries.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BestPractices/BranchNamingConventions.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BestPractices/GoodCommitMessages.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/BestPractices/KeepingReposClean.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitStashAndTag/GitStash.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitStashAndTag/GitStashList.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitStashAndTag/GitTagging.jsx, client/src/pages/Notes/GitVersionControl/GitTopics/GitStashAndTag/TagTypeComparison.jsx
**Hi team 👋**
This PR introduces valuable documentation covering best practices for Git commit messages, branch naming conventions, maintaining a clean repository, and avoiding large binary files in the project. These topics promote maintainability, readability, and performance of the codebase.
---
- There was no clear guidance on writing clear, meaningful commit messages that help in collaboration and project history analysis.
- Branch naming lacked standard conventions, leading to confusion and inconsistent workflows.
- No instructions existed on how to keep the repository clean from clutter, unnecessary files, or large binaries that can bloat the repo.
---
- **Added:** Writing Good Commit Messages
- Best practices such as using imperative mood, limiting subject line length, separating …
=> Add Notes for Writing Good Commit Messages, Branch Name Conventions, Clean Repo, and Avoiding Large Binaries

client/src/components/HomePageComponents/Testimonials.jsx
Description : Button ow redirect to roadmap page
---
- Added: [Description]
- Fixed: [Description]
- Updated: [Description]
---
---
---
---
=> add redirect

client/src/components/CodePlayground.jsx, client/src/pages/CodeEditor.jsx
---
title: "PR: [Brief Description]"
labels: ""
assignees: ""
---
---
- Added: A dropdown menu for selecting languages in smaller screens.
- Fixed: The language selection tabs (JavaScript, Python, C++, C) appear cut off or misaligned on smaller mobile screens. The horizontal button layout does not adapt well to limited screen width, causing a poor user experience.
- Updated: Replaced the horizontal tab buttons with a dropdown menu when viewed on smaller screens (e.g., under 600px width).
---
---
| 
---
---
=> code language menu  responsive 📱
